### ISSUE TITLE
Unknown message: 2024-10-02T06:33:13.913Z INFO  [sm_agent::edge_connection] UserStatus:

### ISSUE THREAD

**Issue by SuzuyaBish** [supermaven-inc/supermaven-nvim#111]
Updated supermaven-nvim through lazy, it downloaded a new binary. I quit and restarted nvim and have been getting this message:

```bash
08:33:13 msg_show [supermaven-nvim] Unknown message: 2024-10-02T06:33:13.913Z INFO  [sm_agent::edge_connection] UserStatus: Pro <my email address>
```

This is from the `supermaven-nvim.log` in cache:

```bash
[DEBUG  Wed Oct  2 08:32:28 2024] Unknown message: 2024-10-02T06:32:28.893Z INFO  [sm_agent] Starting sm-agent
[DEBUG  Wed Oct  2 08:32:28 2024] Unknown message: 2024-10-02T06:32:28.898Z INFO  [sm_agent::edge_connection] Starting new edge connection
[DEBUG  Wed Oct  2 08:32:30 2024] Unknown message: 2024-10-02T06:32:30.189Z INFO  [sm_agent::edge_connection] UserStatus: Pro <my email address>
[DEBUG  Wed Oct  2 08:32:30 2024] Unknown message: 2024-10-02T06:32:30.192Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
[DEBUG  Wed Oct  2 08:32:30 2024] Unknown message: 2024-10-02T06:32:30.199Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
[DEBUG  Wed Oct  2 08:32:30 2024] Unknown message: 2024-10-02T06:32:30.523Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
[DEBUG  Wed Oct  2 08:32:30 2024] Unknown message: 2024-10-02T06:32:30.695Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
[DEBUG  Wed Oct  2 08:32:31 2024] Unknown message: 2024-10-02T06:32:31.456Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
[DEBUG  Wed Oct  2 08:32:31 2024] Unknown message: 2024-10-02T06:32:31.566Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
[DEBUG  Wed Oct  2 08:32:36 2024] Unknown message: 2024-10-02T06:32:36.553Z WARN  [sm_agent::edge_connection] Error from edge server: no active file
```

**Comment by soeguet** [comment]
Same as last time; pinning the plugin to a specific commit will help for the time being. Like:

```lua
return {
	"supermaven-inc/supermaven-nvim",
	commit = "40bde487fe31723cdd180843b182f70c6a991226",
	opts = {}
}
```

**Comment by imjoshnewton** [comment]
> Same as last time; pinning the plugin to a specific commit will help for the time being. Like:
> 
> ```lua
> return {
> 	"supermaven-inc/supermaven-nvim",
> 	commit = "40bde487fe31723cdd180843b182f70c6a991226",
> 	opts = {}
> }
> ```

This worked to roll back to the previous commit and stop the constant error messages.

**Comment by JadoJodo** [comment]
I'm glad that it's not just me. I'm new to Nvim and had just setup LazyGit when it started. Between the constant notifications and the Supermaven messages about "git activity", I (mistakenly) assumed Supermaven was sending LazyGit GUI stuff to Supermaven due to an issue with my config (and that it was breaking things).

Pinning to the commit worked. I'll wait for an update here...

**Comment by sm-victorw** [comment]
I've reverted the merge for now, sorry for the errors.
In your case was the issue just regarding these error messages? Or was plugin functionality affected as well?

**Comment by SuzuyaBish** [comment]
> I've reverted the merge for now, sorry for the errors. In your case was the issue just regarding these error messages? Or was plugin functionality affected as well?

It was just the errors, functionallity was fine over all.

**Comment by imjoshnewton** [comment]
Same - functionality was fine just constant error messages

**Comment by sm-victorw** [comment]
The issue here seems to have mainly occurred as a result due the logging module not properly respecting the default `info` level, which should not have been printing `debug` messages. I've written a patch, please let me know if you experience anything similar.

For error messages messages specifically, if they are ever obtrusive or are providing unhelpful information, they can be disabled completely by setting `log_level = "off"` in the config
