### ISSUE TITLE
Add config option to silence "Supermaven ... is running"

### ISSUE THREAD

**Issue by sQVe** [supermaven-inc/supermaven-nvim#18]
Hey,

I would appreciate it if there was an option to silence the `Supermaven Pro is running` message. It's just noisy and doesn't really provide any value for me.

Cheers!

**Comment by super-jacob** [comment]
Fixed by https://github.com/supermaven-inc/supermaven-nvim/pull/21

**Comment by sQVe** [comment]
@super-jacob As far as I can tell #21 only fixes https://github.com/supermaven-inc/supermaven-nvim/issues/3.

This issue is asking for a config option to completely silence the "Supermaven Pro is running" messages. I try to keep my setup as minimal as possible, and the message just adds noise while providing little value.

**Comment by AlejandroSuero** [comment]
I think that the best way to approach this would be like other plugins does this kind of things.

Create a logger that if the config passes `debug = true`, logs out to the neovim cmdline, otherwise logs out to a file on the plugin folder like `./logs/supermaven-nvim.log`.

Then we use a function like this for example:

```lua
-- logger file
function Logger:log(level, debug, msg)
  if not debug then
  -- write to file
  return
  end
  -- write to file
  -- vim.notify("[supermaven-nvim] " .. level .. ": msg, vim.log.levels[level], { title = "Supermaven" })
end

function Logger:log_fmt(level, debug, msg, ...)
  if not debug then
  -- write to file
  return
  end
  -- write to file
  -- vim.notify("[supermaven-nvim] " .. level .. ": msg, vim.log.levels[level], { title = "Supermaven" })
end
```

```lua
-- print("Supermaven " .. tier .. " is running")
Logger.log_fmt("INFO", debug, "Supermaven %s is running", tier)
```

---

**PLUGINS EXAMPLES**

- [none-ls.nvim](https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/logger.lua)

> I don't know anymore from the top of my head 😥

**Comment by AlejandroSuero** [comment]
@sQVe I added the option and the information on how to use, making use of a logging system.
