### ISSUE TITLE
Supermaven "Error starting binary" in AstroNvim & LunarVim(Lazy.nvim)

### ISSUE THREAD

**Issue by ARKye03** [supermaven-inc/supermaven-nvim#31]
I added this in supermaven.lua in plugins dir(According to [this](https://docs.astronvim.com/configuration/customizing_plugins/)):
```lua
-- if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE
return {
  {
    "supermaven-inc/supermaven-nvim",
    config = true,
  },
}
```
It installs supermaven(And adds the corresponding commands for its usage), but it doesn't work and returns "Error starting binary" every time I type(and when I start AstroNvim) and nothing more, the logs says nothing, I had the same error in LunarVim. Thanks in advance! 
System Info:
- Arch Linux

- nvim --version
    - NVIM v0.10.0
    - Build type: Release
    - LuaJIT 2.1.1713773202

- Latest [AstroNvim](https://astronvim.com/)

On [LunarVim](https://www.lunarvim.org/) I added this line:
```lua
require("lazy").setup({
    {
      "supermaven-inc/supermaven-nvim",
      config = function()
        require("supermaven-nvim").setup({})
      end,
    },
}, {})
```
And didn't work either, the error was the same as AstroNvim. In both cases I'm using [Lazy.nvim](https://github.com/folke/lazy.nvim)

**Comment by AlejandroSuero** [comment]
I just tested it out on a `MacOS 14.5` with default [AstroNvim](https://docs.astronvim.com/#-installation) download, just adding `lua/plugins/supermaven.lua` with the config provided in the issue, and had no problems. I will check later in a `Manjaro` that I have.

Neovim version:

```bash
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```

The issue is triggered at:

https://github.com/supermaven-inc/supermaven-nvim/blob/264768c6b2a2e0480868e9dae443112e33b1484a/lua/supermaven-nvim/binary/binary_handler.lua#L29-L56

If it only says `Error starting binary`, try changing it locally from `print("Err...")` to `error("Err...", vim.log.levels.ERROR)` to see the stacktrace in case it reveals something else.

**Comment by ARKye03** [comment]
I have a NixOS laptop with lunarvim in it, there the plugin works as expected. So I'll take a guess and say that the issue is on my main PC with Arch Linux, however I can't find such conflict, once I get home I'll try  "debug" that piece of code.

**Comment by abhishek-kaith** [comment]
In Arch Linux, I'm encountering the same error even after attempting to downgrade Lua and Neovim. Could it be that the Supermaven binary has dependencies which is missing on my system?

**Comment by abhishek-kaith** [comment]
Hey, the problem disappeared once I deleted the .supermaven folder (using rm -rf ~/.supermave). Neovim downloaded a new binary upon opening, and now everything's functioning smoothly.

**Comment by ARKye03** [comment]
> Hey, the problem disappeared once I deleted the .supermaven folder (using rm -rf ~/.supermave). Neovim downloaded a new binary upon opening, and now everything's functioning smoothly.

Well, it worked for me too, thanks I can finally use supermaven on Arch
