### ISSUE TITLE
Warning: vim.tbl_flatten is deprecated, use vim.iter(…):flatten():totable() instead.

### ISSUE THREAD

**Issue by Frestein** [supermaven-inc/supermaven-nvim#90]
### Problem

vim.tbl_flatten is deprecated.

### Description

The current version of the plugin uses the vim.tbl_flatten function, which has been marked as deprecated. This may lead to compatibility issues with future versions of Neovim.

### Solution

Use vim.iter(…):flatten():totable() instead.

### Neovim version (nvim -v)

NVIM v0.10.1

**Comment by AlejandroSuero** [comment]
@Frestein this is the only place where it is used:

https://github.com/supermaven-inc/supermaven-nvim/blob/2d10d6c63a2c251e8f90d6f80faf4e9c1b8aa7d0/lua/supermaven-nvim/logger.lua#L9-L16

I'm using `v0.10.1` and the `nightly` version, it doesn't throw any messages, does it throw it to you?

**Comment by Frestein** [comment]
> I'm using `v0.10.1` and the `nightly` version, it doesn't throw any messages, does it throw it to you?

@AlejandroSuero Yes, I am receiving the corresponding warning. 

![image](https://github.com/user-attachments/assets/52d7bbf0-acec-48f1-afc9-ce180c9a527c)

The solution was taken from this issue: https://github.com/lukas-reineke/indent-blankline.nvim/issues/866.

**Comment by AlejandroSuero** [comment]
@Frestein that's `lua_ls` indicating that in your version `> v0.10.0` it's deprecated, but if you were using `v0.9` for example or lower it will be using `vim.tbl_flatten`.

For versions 0.10 and higher (0.11 nightly) it is using `vim.iter(...):flatten():totable()`.

In the snippet I linked, `vim.version()` will print all related to the versions, `vim.version().major = 0, vim.version().minor = 10, vim.version().patch = 1` for the current stable, since it's checking for the minor (10) or greater than that, it wouldn't create a compatibility issue.

**Comment by Frestein** [comment]
> @Frestein that's `lua_ls` indicating that in your version `> v0.10.0` it's deprecated, but if you were using `v0.9` for example or lower it will be using `vim.tbl_flatten`.
> 
> For versions 0.10 and higher (0.11 nightly) it is using `vim.iter(...):flatten():totable()`.
> 
> In the snippet I linked, `vim.version()` will print all related to the versions, `vim.version().major = 0, vim.version().minor = 10, vim.version().patch = 1` for the current stable, since it's checking for the minor (10) or greater than that, it wouldn't create a compatibility issue.

I apologize for the misunderstanding. ;)
I only noticed the warning and didn't read the code itself. It would also be a good idea to add ---@diagnostic disable-next-line: deprecated to suppress the warning. Thank you for your clarification!
