### ISSUE TITLE
LSP Kind Symbol doesn't show in nvim-cmp

### ISSUE THREAD

**Issue by lucazz** [supermaven-inc/supermaven-nvim#97]
Hello there everyone, first of all, thank you for this amazing project!

I'm trying to set it up to use as another nvim-cmp source with the following config:
```lua
local lspkind = require "lspkind"
vim.api.nvim_set_hl(0, "CmpItemKindSupermaven", { fg = "#a6e3a1" })

return {
  {
    "supermaven-inc/supermaven-nvim",
    opts = {
      log_level = "warn",
      disable_keymaps = true,
      disable_inline_completion = true,
      condition = function() return false end,
    },
  },
  {
    "hrsh7th/nvim-cmp",
    opts = {
      view = {
        entries = "custom",
      },
      performance = {
        debounce = 0,
        throttle = 0,
      },
      sources = {
        { name = "supermaven" },
        { name = "nvim_lsp" },
        { name = "buffer" },
        { name = "path" },
      },
      formatting = {
        format = lspkind.cmp_format {
          mode = "symbol",
          max_width = 50,
          symbol_map = { Supermaven = "" },
        },
      },
    },
  },
}
```

It works as expected and shows suggestions on cmp, but its missing the LSP Kind symbol:
<img width="1260" alt="Screenshot 2024-09-16 at 11 42 19" src="https://github.com/user-attachments/assets/46bb7016-6161-41d0-9121-8a61a843ab6e">

What am I missing here?

**Comment by AlejandroSuero** [comment]
@lucazz With my `nvim-cmp` config there is no problem:

![nvim-cmp config](https://github.com/user-attachments/assets/4555fc22-021e-4515-94fb-25c52c454a6b)

![supermaven with cmp symbol](https://github.com/user-attachments/assets/ba6e364d-9874-409e-82d4-f4c0c2c62661)

Maybe is because you are setting it up in the `opts` table and requiring `lspkind` and setting the hl before it loads `nvim-cmp` and sets up the plugin.

If I use your config, this happens:

![loading and requiring lspkind first](https://github.com/user-attachments/assets/2b2fd55d-068f-4b33-897b-0468ba22ae75)

If I load it this way, it works:

```lua
return {
  {
    "hrsh7th/nvim-cmp",
    priority = 100,
    opts = {
      view = {
        entries = "custom",
      },
      performance = {
        debounce = 0,
        throttle = 0,
      },
      sources = {
        { name = "supermaven" },
        { name = "nvim_lsp" },
        { name = "buffer" },
        { name = "path" },
      },
    },
    config = function(_, opts)
      local lspkind = require "lspkind"
      opts["formatting"] = {
        format = lspkind.cmp_format {
          mode = "symbol",
          max_width = 50,
          symbol_map = { Supermaven = "" },
        },
      }
      require("cmp").setup(opts)
      vim.api.nvim_set_hl(0, "CmpItemKindSupermaven", { fg = "#a6e3a1" })
    end,
  },
}
```

> [!note]
> I had to insert `formatting` inside config otherwise wouldn't work.

**Comment by lucazz** [comment]
Heya @AlejandroSuero, thank you for getting back to me. That indeed did the trick!
Much appreciated.
